spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/community
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100 # in query를 몇개 날릴 것이냐


logging:
  level:
    org.hinernate.SQL: debug
    #org.hibernate.type: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
